name: 05 Part 1 - Filters Activity Types

on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running when a pull request is opned or synchronized AND base branch is main"