name: 04 - Leveraging Third Party Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # 0. Checkout the code from the repo
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: ls
